version: '3'

services:
  database:
    image: postgres:12-alpine
    container_name: ecs_database
    environment:
      - POSTGRES_USER=ecs
      - POSTGRES_PASSWORD=ecs
      - POSTGRES_DATABASE=ecs
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    restart: always

networks:
  default:
    external:
      name: ecs-reverse-proxy
