version: '3'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: ecs_mailserver
    hostname: ${HOST}
    environment:
      - LOG_LEVEL=debug
      - PERMIT_DOCKER=host
      - ENABLE_AMAVIS=0
      - SMTP_ONLY=1
      - SSL_TYPE=letsencrypt
      # - POSTFIX_INET_PROTOCOLS=ipv4
    volumes:
      - ../data/docker-mailserver/mail-data/:/var/mail/
      - ../data/docker-mailserver/mail-state/:/var/mail-state/
      - ../data/docker-mailserver/mail-logs/:/var/log/mail/
      - ../data/docker-mailserver/config/:/tmp/docker-mailserver/
      - ../data/acme/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

networks:
  default:
    external:
      name: ecs-reverse-proxy
